# Generated by Django 4.0.2 on 2022-02-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_id_alter_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
