# Generated by Django 4.0.2 on 2022-02-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_categoria_remove_proveedor_id_alter_proveedor_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='personacontacto',
            field=models.CharField(max_length=50, verbose_name='Persona Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='region',
            field=models.CharField(max_length=200, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Teléfono'),
        ),
    ]
